services:

  #------------------------------------
  # PostgreSQL container:
  postgres:
    container_name: hpc-usage-postgres
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    volumes:
      - hpc-usage-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - hpc-usage-network

networks:
  hpc-usage-network:
    driver: bridge

volumes:
  hpc-usage-postgres-data:
